apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloK8s.name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.helloK8s.port }}
    targetPort: {{ .Values.helloK8s.targetPort }}
  selector:
    app: {{ .Values.helloK8s.appLabel }}