apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.nginx.port }}
    protocol: TCP
    targetPort: {{ .Values.nginx.targetPort }}
  selector:
    app: {{ .Values.nginx.appLabel }}
